// A framed oil painting on the wall — bought for this room (generated by Suede AI, paid in USDC) and
// shipped with the app in public/art, so nothing is fetched from the internet at run time.
// Gilded frame, cream mat, a brass picture light that washes the canvas, and a small plaque.
import { useEffect, useState } from 'react'
import { Object3D, SRGBColorSpace, TextureLoader } from 'three'
import { Label } from './Label'

const ART = `${import.meta.env.BASE_URL}art/meadow-painting.jpg`
const W = 1.68, H = 0.96 // the canvas (1344 × 768 picture)

export function Painting({ title = 'Golden Meadow', ...props }) {
  const [map, setMap] = useState(null)
  const [aim] = useState(() => new Object3D())
  useEffect(() => {
    let live = true, tex
    new TextureLoader().load(ART, (t) => {
      t.colorSpace = SRGBColorSpace
      t.anisotropy = 8
      tex = t
      if (live) setMap(t); else t.dispose()
    })
    return () => { live = false; tex?.dispose() }
  }, [])
  const gold = <meshStandardMaterial color="#b48a4a" roughness={0.35} metalness={0.75} />
  const F = 0.09, MAT = 0.07 // frame and mat widths
  const ow = W + 2 * MAT, oh = H + 2 * MAT
  return (
    <group name="painting" {...props}>
      {/* frame: four gilded rails with an inner bead */}
      <mesh name="painting frame" position={[0, oh / 2 + F / 2, 0.03]} castShadow>{gold}<boxGeometry args={[ow + 2 * F, F, 0.06]} /></mesh>
      <mesh name="painting frame" position={[0, -oh / 2 - F / 2, 0.03]} castShadow>{gold}<boxGeometry args={[ow + 2 * F, F, 0.06]} /></mesh>
      <mesh name="painting frame" position={[-ow / 2 - F / 2, 0, 0.03]} castShadow>{gold}<boxGeometry args={[F, oh, 0.06]} /></mesh>
      <mesh name="painting frame" position={[ow / 2 + F / 2, 0, 0.03]} castShadow>{gold}<boxGeometry args={[F, oh, 0.06]} /></mesh>
      {/* mat and canvas */}
      <mesh name="painting mat" position-z={0.012} receiveShadow>
        <boxGeometry args={[ow, oh, 0.02]} />
        <meshStandardMaterial color="#efe6d6" roughness={0.95} />
      </mesh>
      <mesh name="painting canvas" position-z={0.024} receiveShadow>
        <planeGeometry args={[W, H]} />
        <meshStandardMaterial map={map} color={map ? '#ffffff' : '#a8875f'} roughness={0.8} />
      </mesh>

      {/* brass picture light over the frame */}
      <group position={[0, oh / 2 + F + 0.1, 0]}>
        <mesh name="picture light arm" position={[0, 0, 0.08]} rotation-x={Math.PI / 2}>
          <cylinderGeometry args={[0.012, 0.012, 0.16, 10]} />
          <meshStandardMaterial color="#9c7a3c" roughness={0.3} metalness={0.8} />
        </mesh>
        <mesh name="picture light" position={[0, 0, 0.17]} rotation-z={Math.PI / 2} castShadow>
          <cylinderGeometry args={[0.035, 0.035, 0.7, 20]} />
          <meshStandardMaterial color="#9c7a3c" roughness={0.3} metalness={0.8} />
        </mesh>
        <mesh name="picture light glow" position={[0, -0.034, 0.17]} rotation-x={Math.PI / 2}>
          <planeGeometry args={[0.66, 0.02]} />
          <meshBasicMaterial color="#ffe2b0" toneMapped={false} />
        </mesh>
        <primitive object={aim} position={[0, -0.6, 0]} />
        <spotLight target={aim} position={[0, -0.03, 0.2]} angle={0.95} penumbra={0.8} intensity={2.2} distance={2.4} decay={2} color="#ffd9a8" />
      </group>

      {/* plaque */}
      <group position={[0, -oh / 2 - F - 0.1, 0.012]}>
        <mesh name="painting plaque"><boxGeometry args={[0.52, 0.1, 0.012]} /><meshStandardMaterial color="#2a2219" roughness={0.5} metalness={0.3} /></mesh>
        <Label text={title} name="painting title" size={0.055} weight={600} color="#e9cf9a" width={0.48} position-z={0.008} />
      </group>
    </group>
  )
}
